# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_code', models.CharField(blank=True, max_length=4)),
                ('pdb_chain', models.CharField(blank=True, max_length=1)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
