# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
        ('molecule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='prot',
            field=models.ManyToManyField(to='protein.Protein'),
        ),
    ]
