# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubchem_id', models.PositiveIntegerField(blank=True)),
                ('common_name', models.CharField(max_length=255)),
                ('chemical_name', models.CharField(max_length=255)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Protein')),
            ],
        ),
    ]
