# Generated by Django 2.2.8 on 2019-12-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protein.Protein'),
        ),
    ]
